### ISSUE TITLE
Create one repo that contains all the code necessary to create a new site from scratch

### ISSUE THREAD

**Issue by mallorydxw** [dxw/wordpress-template#1]
This is currently split between multiple repos:

The app repo structure is stored in `whippet`'s app generator: https://github.com/dxw/whippet/tree/main/generators/app/template
- The theme template is in this repo: https://github.com/dxw/whippet-theme-template
- And the code for running everything in Docker is here: https://github.com/dxw/wpc

The Rails team has one of these: https://github.com/dxw/rails-template

They can click "Use this template" to create a new GitHub repo containing everything they need.

**Comment by RobjS** [comment]
I'd really like to get to the stage where it's possible to generate a new site and get it running locally using nothing more than git, php & composer, and docker - i.e. you shouldn't need any custom tools (like whippet) installed before you start. 

We're already one step along with this by including whippet as a composer dev dependency in the root of projects, so you can run `vendor/bin/whippet` rather than needing whippet installed separately.

**Comment by mallorydxw** [comment]
I've added some commits to the `main` branch so I think this ticket can be closed.

> I'd really like to get to the stage where it's possible to generate a new site and get it running locally using nothing more than git, php & composer, and docker - i.e. you shouldn't need any custom tools (like whippet) installed before you start.

But let's keep this in mind.
