### ISSUE TITLE
Formalise the relationship between this and wpc

### ISSUE THREAD

**Issue by mallorydxw** [dxw/wordpress-template#41]
- Should we remove the template from wpc and have this be the only template?
- Should wpc from now on just contain the `thedxw/wpc-wordpress` image?
- Should we create a `v2` of the image so that we can make breaking changes?
- Mention this in the READMEs of both projects

**Comment by RobjS** [comment]
We could make wpc a composer dependency that does its thing in the initial `script/setup` run.

**Comment by RobjS** [comment]
Reading that last comment again, I have no idea what I meant there. 🤦 

I think turning wpc into a repo that just contains the `thedxw/wpc-wordpress` image makes sense. 

I'm less certain of what to do with all the associated scripts. One option would be for them live in a standalone composer package, so that if we want to update them globally in future, it's just a question of updating that package and running `composer update` in each project repo. We could keep the `scripts/` folder in `wordpress-template`, and just have the files in there point to the relevant `vendor/bin` scripts.

We should also be able to keep the `setup/internal.sh` within each project repo, allowing the project-specific part of scripts to continue to live within individual project repos.
