### ISSUE TITLE
Should this repo include a theme template and a plugin template?

### ISSUE THREAD

**Issue by mallorydxw** [dxw/wordpress-template#5]
I think this repo should probably include the theme template. Most of the sites we've made, we create a new theme for it. Most of the themes we have, are part of the repo rather than their own repo.

And I think we should put the plugin template in a separate repo. Most of the plugins we've made live in their own repo and are included via `whippet deps install` (though we also have a lot that live in the main app repo).

- [x] Include our theme template in here
- [ ] Create a separate repo for our plugin template

**Comment by RobjS** [comment]
I've been pondering this too. There are a couple of advantages to the way `whippet generate theme` works that we'd be potentially losing/compromising if our base theme was part of a template:

- The ability to quickly generate a theme independently of the app as a whole
- The auto-namespacing that Whippet does for you as part of that theme generation. I feel like replacing that with the manual search/replace the rails template relies upon would be a downgrade.

Thinking about this also raises some questions around the base functionality that is included in Whippet Theme Template, particularly here: https://github.com/dxw/whippet-theme-template/tree/main/app/Theme:

- Do we use those classes exactly as-is across the majority of our repos? If so, should they be wrapped up in a separate package, rather than repeated as part of a template, so that we can manage them in a single place?
- If we don't use them, should we remove them altogether? Or are they still useful as a starting point?

I don't really have answers to any of these things at the moment, but I think they're worth discussing.

**Comment by mallorydxw** [comment]
> The auto-namespacing that Whippet does for you as part of that theme generation. I feel like replacing that with the manual search/replace the rails template relies upon would be a downgrade.

What if we included a first-run script? So you run it immediately after creating a new repo from the template - i.e. `./start` and it does a search/replace for a bunch of things and then deletes itself?

> Do we use those classes exactly as-is across the majority of our repos?

For https://github.com/dxw/whippet-theme-template/blob/main/app/Theme/Scripts.php at least, it's used as a starting point which we then edit when we want to add new things.

**Comment by RobjS** [comment]
I think this can be closed now. We have a theme template in the repo, and we've got two separate repos for a plugin template: 
https://github.com/dxw/wordpress-plugin-template
https://github.com/dxw/whippet-plugin-template

See https://trello.com/c/BcJgNuXb/26-make-whippet-generate-plugins
